### ISSUE TITLE
Nav Bar Light Up Sequence

### ISSUE THREAD

**Issue by alyons-dm** [Digitalminion/DM-ng-legacy-foolish-endeavor#24] opened 2017-03-01 04:10 UTC
I would like to make the nav bar light up in sequence with the astronauts, and dim as the astronauts walk back over:

![mockupnavbar-01](https://cloud.githubusercontent.com/assets/20231883/23445659/eacb2b50-fdf1-11e6-9a62-10a06c1873e2.png)

**Comment by dataminion** [comment] 2017-03-06 19:21
So I think this is a good idea, I would add the caveat that the navigation needs to be clear so if you are going to animate by lighting up, then you need to differentiate the "active page another way for example by having the active page be underlined

**Comment by alyons-dm** [comment] 2017-03-07 00:38
I've doen 2 commits so far to update the existing code with the clashing code changes I had made in ng-timeout previously. Currently trying to determine the best way to make the home button stand out, as this animation will only ever take place on the home page. I am most likely just going to underline it though, as Austin suggested

**Comment by alyons-dm** [comment] 2017-03-07 00:39
After i get these to all light up though, I would also like to add to this ticket that the font needs to be changed. In my mockup, I had it match the original typewriter style typeface. I would like to incorporate that here as well.

**Comment by alyons-dm** [comment] 2017-03-07 04:24
I believe I am done with this ticket. I reimplemented the original code that conflicted on the other ng-timeout and got the home button to underline.

**Comment by jfn6030217** [comment] 2017-03-07 15:03
When the very first step is taken, 
![2017-03-07_8-59-27](https://cloud.githubusercontent.com/assets/11492233/23662264/96cbe7ec-0314-11e7-9572-98b3328b5f98.png)
the "Home" is not lit underneath the Pilot.  

The "Home" button remains synced differently from the other words throughout the animation (ie, "Home" and "About" are not lit at the same time as in the mockups above).

Could you please review and revise if possible?

**Comment by jfn6030217** [comment] 2017-03-07 15:26
After a code review, I recommend that the <md-button> names ("link_1", "link_2") should be more descriptive.  I recommend something like "link_home", "link_about", etc, which will help those that read your code understand immediately which element is being modified, instead of needing to cross-reference it.

**Comment by alyons-dm** [comment] 2017-03-08 08:53
I believe I have completed the revisions to this ticket!

**Comment by jfn6030217** [comment] 2017-03-08 16:27
After a functional review, the behavior is as proposed

**Comment by jfn6030217** [comment] 2017-03-08 16:35
After a code review, it is observed that the "Home is not lit underneath the pilot" issue is resolved by hardcoding a new initial color (white) and initiating the "walk" without waiting for the mouse to enter the svg area.  This behvaior is consistent with the original "develop" behavior, but is not what was intended by previous tickets (ie, this is a regression).  

The code is acceptable, but this points us towards some technical debt which we need to create a new ticket to resolve -- None of the walkers should show up until the cursor enters the svg, and by extension, none of the words should be white until the walking begins.

**Comment by jfn6030217** [comment] 2017-03-08 21:33
After discussion, we decided that the animation should not be beginning until the mouse hovers over the svg (the technical debt pointed out in the previous comment), and so Ariel has requested that this ticket be returned to her for looking into that.

**Comment by jfn6030217** [comment] 2017-03-14 17:49
Based on your commit that it was semi-working, I have refactored the code to do the right thing.  However, I haven't completed this work.  Please don't work on this ticket until you hear back from me (in a day or so)

**Comment by alyons-dm** [comment] 2017-03-16 00:04
So, I had trouble getting anything to happen at first but it's because I forgot to call timeout correctly. Now it's loading the first two simultaneously and throwing"oops" into the console a lot. trying to figure out the troubleshoot now

**Comment by alyons-dm** [comment] 2017-03-16 00:27
Ok, so now I cant get the text to light up in sequence, AND if I set the board to not start until I hover over it, I can't seem figure out how to make that just a one time thing/ to have it stop when i unhove, but continue from where it left off when I re-hover. Every time I hover it restarts again.

**Comment by alyons-dm** [comment] 2017-03-16 01:04
I believe I have completed everything in this ticket!

**Comment by jfn6030217** [comment] 2017-03-20 22:29
This ticket has been successfully completed, and a merge-down has occurred.  It may now be closed.

**Closed as completed by jfn6030217** 2017-03-20 22:29 UTC
Labels: Ready Review
